version: "3.9"

services:
  task-manager-container:
    image: task-manager
    ports:
      - "127.0.0.1:8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - C:/Users/HP/Desktop/HSE/year2/projects/task-manager/task_app/temlates:/usr/source/app/task_app/templates
    # depends_on:
    #   - db

  # db:
  #   image: postgres:14
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data/
  #   environment:
  #     POSTGRES_DB: "task_db"
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "postgres"
  #   ports:
  #     - "5432:5432"
