# Generated by Django 4.1.3 on 2022-11-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='task_type_name',
            field=models.CharField(choices=[('SERVICE', 'Сервисная задача'), ('ANALITICS', 'Аналитическая задача'), ('RESEARCH', 'Исследовательская задача')], help_text='Категория задачи', max_length=50),
        ),
    ]
