# Generated by Django 4.1.3 on 2022-11-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_alter_tasktype_task_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline_date']},
        ),
    ]
