# Generated by Django 4.1.3 on 2022-11-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_alter_tasktype_task_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Описание задачи', null=True),
        ),
    ]
