# Generated by Django 4.1.3 on 2022-11-22 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_app', '0005_task_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertask',
            options={'verbose_name': "User's task"},
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(blank=True, help_text='Дедлайн для задачи', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_of_type', to='task_app.tasktype'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='task_type_name',
            field=models.CharField(choices=[('SERVICE', 'Сервисная задача'), ('ANALITICS', 'Аналитическая задача'), ('RESEARCH', 'Исследовательская задача')], default=None, help_text='Категория задачи', max_length=50),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='task',
            field=models.ForeignKey(help_text='Выбранная задача', on_delete=django.db.models.deletion.CASCADE, related_name='tasks_user', to='task_app.task'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(help_text='Исполнитель задачи', on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
