# Generated by Django 4.1.3 on 2022-11-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0011_alter_tasktype_task_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='task_type_name',
            field=models.CharField(choices=[('SERVICE', 'Сервисная задача'), ('ANALITICS', 'Аналитическая задача'), ('RESEARCH', 'Исследовательская задача')], help_text='Категория задачи', max_length=50, unique=True),
        ),
    ]
