# Generated by Django 4.1.3 on 2022-12-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0015_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-deadline_date']},
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(help_text='Дедлайн для задачи', null=True),
        ),
    ]
