# Generated by Django 4.1.3 on 2022-12-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0016_alter_task_options_alter_task_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(help_text='Дедлайн для задачи'),
        ),
    ]
