# Generated by Django 4.1.3 on 2022-12-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0017_alter_task_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(blank=True, help_text='Дедлайн для задачи', null=True),
        ),
    ]
